### ISSUE TITLE
useEffect generates additional (unwanted) error

### ISSUE THREAD

**Issue by Arcasias** [odoo/owl#1149]
**Scenario**
```js
class Root extends owl.Component {
    static template = owl.xml`<div />`;
    setup() {
        owl.useEffect(
            () => {
                throw new Error("Intentional error");
            },
            () => []
        ); 
    }
}

try {
    await owl.mount(Root, document.body, { dev: true });
} catch (err) {
    /** Error caught! */
}
```
**Problem**
Even though the error is caught, the execution of the `useEffect` hook was disturbed and its `cleanup` is not assigned, hence generating an additional error in the console:
```
owl.js:1941 Error: The following error occurred in onWillUnmount: "cleanup is not a function"
    at wrapError (owl.js:4839:23)
    at onWillUnmount (owl.js:4893:34)
    at Object.useEffect (owl.js:5450:9)
    at Root.setup (about:blank:6:13)
    at new ComponentNode (owl.js:2390:28)
    at App.makeNode (owl.js:5321:20)
    at App.mount (owl.js:5315:31)
    at Object.mount (owl.js:5359:35)
    at about:blank:16:15
    at about:blank:21:11
```
I think this error is unnecessary since it's a result of the fallback not being correctly applied, and the rendering process would have already been interupted by the first error anyway.

**Comment by ged-odoo** [comment]
on it
