### ISSUE TITLE
[owl tutorial] ]owl.js:1 Uncaught (in promise) Error: Cannot mount component: the target is not a valid DOM element

### ISSUE THREAD

**Issue by jackadam1981** [odoo/owl#1218]
i'm follow OWL Tutorial: TodoApp to learn OWL.
1.Setting up the project is good. console pring my log.
2.Adding a first component is error.

I try different js include [REL] v1.4.10。

Errors are reported as follows：

Google Chrome  103.0.5060.53（64 ）

 [owl.iife.min.js](https://github.com/odoo/owl/releases/download/v2.0.0-beta-10/owl.iife.min.js)
owl.iife.min.js:1 Uncaught (in promise) Error: Cannot mount component: the target is not a valid DOM element
    at En.validateTarget (owl.iife.min.js:1:71340)
    at En.mount (owl.iife.min.js:1:69826)
    at t.mount (owl.iife.min.js:1:72985)
    at app.js:8:1

[owl.iife.js](https://github.com/odoo/owl/releases/download/v2.0.0-beta-10/owl.iife.js)
owl.iife.js:2122 Uncaught (in promise) Error: Cannot mount component: the target is not a valid DOM element
    at App.validateTarget (owl.iife.js:2122:19)
    at App.mount (owl.iife.js:5462:17)
    at mount (owl.iife.js:5561:35)
    at app.js:8:1

[owl.cjs.js](https://github.com/odoo/owl/releases/download/v2.0.0-beta-10/owl.cjs.js)
owl.cjs.js:3 Uncaught ReferenceError: exports is not defined
    at owl.cjs.js:3:23
app.js:1 Uncaught SyntaxError: Identifier 'Component' has already been declared (at app.js:1:1)

[owl.es.js](https://github.com/odoo/owl/releases/download/v2.0.0-beta-10/owl.es.js)
owl.es.js:5700 Uncaught SyntaxError: Unexpected token 'export' (at owl.es.js:5700:1)
app.js:1 Uncaught ReferenceError: owl is not defined
    at app.js:1:33

**Comment by jackadam1981** [comment]
it works on [REL] v2.0.0-beta-12
