### ISSUE TITLE
unclear error message

### ISSUE THREAD

**Issue by ged-odoo** [odoo/owl#1550]
If I add a throw error in the setup of a component (see [playground example 1](https://odoo.github.io/owl/playground/#eyJqcyI6Ii8vIEluIHRoaXMgZXhhbXBsZSwgd2Ugc2hvdyBob3cgY29tcG9uZW50cyBjYW4gYmUgZGVmaW5lZCBhbmQgY3JlYXRlZC5cbmltcG9ydCB7IENvbXBvbmVudCwgdXNlU3RhdGUsIG1vdW50IH0gZnJvbSBcIkBvZG9vL293bFwiO1xuXG5jbGFzcyBHcmVldGVyIGV4dGVuZHMgQ29tcG9uZW50IHtcbiAgICBzdGF0aWMgdGVtcGxhdGUgPSBcIkdyZWV0ZXJcIjtcbiAgICBcbiAgICBzZXR1cCgpIHtcbiAgICAgICAgdGhpcy5zdGF0ZSA9IHVzZVN0YXRlKHsgd29yZDogJ0hlbGxvJyB9KTtcbiAgICAgICAgdGhyb3cgbmV3IEVycm9yKFwiYm9vbVwiKTtcbiAgICB9XG5cbiAgICB0b2dnbGUoKSB7XG4gICAgICAgIHRoaXMuc3RhdGUud29yZCA9IHRoaXMuc3RhdGUud29yZCA9PT0gJ0hpJyA/ICdIZWxsbycgOiAnSGknO1xuICAgIH1cbn1cblxuLy8gTWFpbiByb290IGNvbXBvbmVudFxuY2xhc3MgUm9vdCBleHRlbmRzIENvbXBvbmVudCB7XG4gICAgc3RhdGljIGNvbXBvbmVudHMgPSB7IEdyZWV0ZXIgfTtcbiAgICBzdGF0aWMgdGVtcGxhdGUgPSBcIlJvb3RcIlxuXG4gICAgc2V0dXAoKSB7XG4gICAgICAgIHRoaXMuc3RhdGUgPSB1c2VTdGF0ZSh7IG5hbWU6ICdXb3JsZCd9KTtcbiAgICB9XG59XG5cbm1vdW50KFJvb3QsIGRvY3VtZW50LmJvZHksIHsgdGVtcGxhdGVzOiBURU1QTEFURVMsIGRldjogdHJ1ZSB9KTtcbiIsImNzcyI6Ii5ncmVldGVyIHtcbiAgICBmb250LXNpemU6IDIwcHg7XG4gICAgd2lkdGg6IDMwMHB4O1xuICAgIGhlaWdodDogMTAwcHg7XG4gICAgbWFyZ2luOiA1cHg7XG4gICAgdGV4dC1hbGlnbjogY2VudGVyO1xuICAgIGxpbmUtaGVpZ2h0OiAxMDBweDtcbiAgICBiYWNrZ3JvdW5kLWNvbG9yOiAjZWVlZWVlO1xuICAgIHVzZXItc2VsZWN0OiBub25lO1xufVxuIiwieG1sIjoiPHRlbXBsYXRlcz5cbiAgPGRpdiB0LW5hbWU9XCJHcmVldGVyXCIgY2xhc3M9XCJncmVldGVyXCIgdC1vbi1jbGljaz1cInRvZ2dsZVwiPlxuICAgIDx0IHQtZXNjPVwic3RhdGUud29yZFwiLz4sIDx0IHQtZXNjPVwicHJvcHMubmFtZVwiLz5cbiAgPC9kaXY+XG5cbiAgPHQgdC1uYW1lPVwiUm9vdFwiPlxuICAgIDxHcmVldGVyIG5hbWU9XCJzdGF0ZS5uYW1lXCIvPlxuICA8L3Q+XG48L3RlbXBsYXRlcz5cbiJ9)) I have the following confusing error: 
```
owl.js:1576 Uncaught (in promise) Error: An error occured in the owl lifecycle (see this Error's "cause" property)
    at handleError (owl.js:1576:31)
    at App.handleError (owl.js:5784:16)
    at MountFiber._render (owl.js:1722:26)
    at MountFiber.render (owl.js:1711:14)
    at ComponentNode.initiateRender (owl.js:2375:19)
handleError @ owl.js:1576
handleError @ owl.js:5784
_render @ owl.js:1722
render @ owl.js:1711
initiateRender @ owl.js:2375
await in initiateRender (async)
mountComponent @ owl.js:2359
mountNode @ owl.js:5705
mount @ owl.js:5676
mount @ owl.js:5791
(anonymous) @ VM103:37
owl.js:1576 Uncaught (in promise) Error: An error occured in the owl lifecycle (see this Error's "cause" property)
    at handleError (owl.js:1576:31)
    at App.handleError (owl.js:5784:16)
    at MountFiber._render (owl.js:1722:26)
    at MountFiber.render (owl.js:1711:14)
    at ComponentNode.initiateRender (owl.js:2375:19)
```
I think that it was clearer before, i would like to see in the traceback that the error comes from the setup function of the component.

Another example: if there is an error in a template, (see [playground ex2](https://odoo.github.io/owl/playground/#eyJqcyI6Ii8vIEluIHRoaXMgZXhhbXBsZSwgd2Ugc2hvdyBob3cgY29tcG9uZW50cyBjYW4gYmUgZGVmaW5lZCBhbmQgY3JlYXRlZC5cbmltcG9ydCB7IENvbXBvbmVudCwgdXNlU3RhdGUsIG1vdW50IH0gZnJvbSBcIkBvZG9vL293bFwiO1xuXG5jbGFzcyBHcmVldGVyIGV4dGVuZHMgQ29tcG9uZW50IHtcbiAgICBzdGF0aWMgdGVtcGxhdGUgPSBcIkdyZWV0ZXJcIjtcbiAgICBcbiAgICBzZXR1cCgpIHtcbiAgICAgICAgdGhpcy5zdGF0ZSA9IHVzZVN0YXRlKHsgd29yZDogJ0hlbGxvJyB9KTtcbiAgICAgICAgdGhyb3cgbmV3IEVycm9yKFwiYm9vbVwiKTtcbiAgICB9XG5cbiAgICB0b2dnbGUoKSB7XG4gICAgICAgIHRoaXMuc3RhdGUud29yZCA9IHRoaXMuc3RhdGUud29yZCA9PT0gJ0hpJyA/ICdIZWxsbycgOiAnSGknO1xuICAgIH1cbn1cblxuLy8gTWFpbiByb290IGNvbXBvbmVudFxuY2xhc3MgUm9vdCBleHRlbmRzIENvbXBvbmVudCB7XG4gICAgc3RhdGljIGNvbXBvbmVudHMgPSB7IEdyZWV0ZXIgfTtcbiAgICBzdGF0aWMgdGVtcGxhdGUgPSBcIlJvb3RcIlxuXG4gICAgc2V0dXAoKSB7XG4gICAgICAgIHRoaXMuc3RhdGUgPSB1c2VTdGF0ZSh7IG5hbWU6ICdXb3JsZCd9KTtcbiAgICB9XG59XG5cbm1vdW50KFJvb3QsIGRvY3VtZW50LmJvZHksIHsgdGVtcGxhdGVzOiBURU1QTEFURVMsIGRldjogdHJ1ZSB9KTtcbiIsImNzcyI6Ii5ncmVldGVyIHtcbiAgICBmb250LXNpemU6IDIwcHg7XG4gICAgd2lkdGg6IDMwMHB4O1xuICAgIGhlaWdodDogMTAwcHg7XG4gICAgbWFyZ2luOiA1cHg7XG4gICAgdGV4dC1hbGlnbjogY2VudGVyO1xuICAgIGxpbmUtaGVpZ2h0OiAxMDBweDtcbiAgICBiYWNrZ3JvdW5kLWNvbG9yOiAjZWVlZWVlO1xuICAgIHVzZXItc2VsZWN0OiBub25lO1xufVxuIiwieG1sIjoiPHRlbXBsYXRlcz5cbiAgPGRpdiB0LW5hbWU9XCJHcmVldGVyXCIgY2xhc3M9XCJncmVldGVyXCIgdC1vbi1jbGljaz1cInRvZ2dsZVwiPlxuICAgIDx0IHQtZXNjPVwic3RhdGUud29yZFwiLz4sIDx0IHQtZXNjPVwicHJvcHMubmFtZVwiLz5cbiAgPC9kaXY+XG5cbiAgPHQgdC1uYW1lPVwiUm9vdFwiPlxuICAgIDxHcmVldGVyIG5hbWU9XCJzdGF0ZS5uYW1lXCIvPlxuICA8L3Q+XG48L3RlbXBsYXRlcz5cbiJ9))
we get the following traceback:
```
owl.js:1576 Uncaught (in promise) Error: An error occured in the owl lifecycle (see this Error's "cause" property)
    at handleError (owl.js:1576:31)
    at App.handleError (owl.js:5784:16)
    at Fiber._render (owl.js:1722:26)
    at Fiber.render (owl.js:1711:14)
    at ComponentNode.initiateRender (owl.js:2375:19)
handleError @ owl.js:1576
handleError @ owl.js:5784
_render @ owl.js:1722
render @ owl.js:1711
initiateRender @ owl.js:2375
await in initiateRender (async)
(anonymous) @ owl.js:5777
template @ VM240:10
_render @ owl.js:1719
render @ owl.js:1711
initiateRender @ owl.js:2375
await in initiateRender (async)
mountComponent @ owl.js:2359
mountNode @ owl.js:5705
mount @ owl.js:5676
mount @ owl.js:5791
(anonymous) @ VM238:36
owl.js:1576 Uncaught (in promise) Error: An error occured in the owl lifecycle (see this Error's "cause" property)
    at handleError (owl.js:1576:31)
    at App.handleError (owl.js:5784:16)
    at Fiber._render (owl.js:1722:26)
    at Fiber.render (owl.js:1711:14)
    at ComponentNode.initiateRender (owl.js:2375:19)
```
not very useful...

**Comment by ged-odoo** [comment]
we simplified the errors and the call stack in owl 3
