### ISSUE TITLE
White Page Appears When Logged in as Admin After Docker Upgrade

### ISSUE THREAD

**Issue by flowersofpepper** [odoo/owl#1660]
After upgrading Docker, logging in as an admin user results in a white page, rendering the application unusable. The browser console logs an UncaughtPromiseError > OwlError, indicating an issue in the Owl lifecycle. 

`
UncaughtPromiseError > OwlError
Uncaught Promise > An error occurred in the Owl lifecycle (see this Error's "cause" property)
OwlError: An error occurred in the Owl lifecycle (see this Error's "cause" property)
Error: An error occurred in the Owl lifecycle (see this Error's "cause" property)
at handleError (https://example.com/web/assets/2aeef6b/web.assets_web.min.js:916:101)
at App.handleError (https://example.com/web/assets/2aeef6b/web.assets_web.min.js:1551:29)
at Fiber._render (https://example.com/web/assets/2aeef6b/web.assets_web.min.js:941:19)
at Fiber.render (https://example.com/web/assets/2aeef6b/web.assets_web.min.js:939:6)
at ComponentNode.initiateRender (https://example.com/web/assets/2aeef6b/web.assets_web.min.js:1008:47)

Caused by: TypeError: this.env._t is not a function
at RPCErrorDialog.inferTitle (https://example.com/web/assets/2aeef6b/web.assets_web.min.js:14928:58)
at RPCErrorDialog.setup (https://example.com/web/assets/2aeef6b/web.assets_web.min.js:2346:165)
at new ComponentNode (https://example.com/web/assets/2aeef6b/web.assets_web.min.js:1003:202)
at https://example.com/web/assets/2aeef6b/web.assets_web.min.js:1549:6
at DialogWrapper.slot1 (eval at compile (https://example.com/web/assets/2aeef6b/web.assets_web.min.js:1503:374), :11:27)
at callSlot (https://example.com/web/assets/2aeef6b/web.assets_web.min.js:1109:25)
at WithEnv.template (eval at compile (https://example.com/web/assets/2aeef6b/web.assets_web.min.js:1503:374), :8:12)
at Fiber._render (https://example.com/web/assets/2aeef6b/web.assets_we
`

**Comment by sdegueldre** [comment]
I think the error is pretty clear: `TypeError: this.env._t is not a function`.

One of your components is attempting to use `this.env._t`, the translation function is not in the environment in recent versions of Odoo you will need to adapt your code.

This error has nothing to do with Owl itself.
