### ISSUE TITLE
class + t-attf-class not working with ternary expressions

### ISSUE THREAD

**Issue by SoftHeroes** [odoo/owl#725]
I was using **_t-attf-name_** but It's not working in Odoo version 13.

Error Trace : 
```
Error:
Odoo Server Error

Traceback (most recent call last):
  File "D:\Softwares\Odoo 13.0\server\odoo\tools\cache.py", line 85, in lookup
    r = d[key]
  File "D:\Softwares\Odoo 13.0\server\odoo\tools\func.py", line 69, in wrapper
    return func(self, *args, **kwargs)
  File "D:\Softwares\Odoo 13.0\server\odoo\tools\lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.qweb', <function IrQWeb.compile at 0x046CCD20>, 580, ('en_US', True, None, None, None, 1))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Softwares\Odoo 13.0\server\odoo\addons\base\models\qweb.py", line 291, in compile
    body = self._compile_node(element, _options)
  File "D:\Softwares\Odoo 13.0\server\odoo\addons\base\models\qweb.py", line 654, in _compile_node
    return body + self._compile_directives(el, options)
  File "D:\Softwares\Odoo 13.0\server\odoo\addons\base\models\qweb.py", line 675, in _compile_directives
    return compile_handler(el, options)
  File "D:\Softwares\Odoo 13.0\server\odoo\addons\web_editor\models\ir_qweb.py", line 81, in _compile_directive_tag
    return super(QWeb, self)._compile_directive_tag(el, options)
  File "D:\Softwares\Odoo 13.0\server\odoo\addons\base\models\qweb.py", line 1008, in _compile_directive_tag
    content = self._compile_directives(el, options)
  File "D:\Softwares\Odoo 13.0\server\odoo\addons\base\models\qweb.py", line 675, in _compile_directives
    return compile_handler(el, options)
  File "D:\Softwares\Odoo 13.0\server\odoo\addons\base\models\qweb.py", line 1071, in _compile_directive_content
    body.extend(self._compile_node(item, options))
  File "D:\Softwares\Odoo 13.0\server\odoo\addons\base\models\qweb.py", line 645, in _compile_node
    return self._compile_static_node(el, options)
  File "D:\Softwares\Odoo 13.0\server\odoo\addons\base\models\qweb.py", line 801, in _compile_static_node
    content = self._compile_directive_content(el, options)
  File "D:\Softwares\Odoo 13.0\server\odoo\addons\base\models\qweb.py", line 1071, in _compile_directive_content
    body.extend(self._compile_node(item, options))
  File "D:\Softwares\Odoo 13.0\server\odoo\addons\base\models\qweb.py", line 645, in _compile_node
    return self._compile_static_node(el, options)
  File "D:\Softwares\Odoo 13.0\server\odoo\addons\base\models\qweb.py", line 801, in _compile_static_node
    content = self._compile_directive_content(el, options)
  File "D:\Softwares\Odoo 13.0\server\odoo\addons\base\models\qweb.py", line 1071, in _compile_directive_content
    body.extend(self._compile_node(item, options))
  File "D:\Softwares\Odoo 13.0\server\odoo\addons\base\models\qweb.py", line 645, in _compile_node
    return self._compile_static_node(el, options)
  File "D:\Softwares\Odoo 13.0\server\odoo\addons\base\models\qweb.py", line 801, in _compile_static_node
    content = self._compile_directive_content(el, options)
  File "D:\Softwares\Odoo 13.0\server\odoo\addons\base\models\qweb.py", line 1071, in _compile_directive_content
    body.extend(self._compile_node(item, options))
  File "D:\Softwares\Odoo 13.0\server\odoo\addons\base\models\qweb.py", line 654, in _compile_node
    return body + self._compile_directives(el, options)
  File "D:\Softwares\Odoo 13.0\server\odoo\addons\base\models\qweb.py", line 675, in _compile_directives
    return compile_handler(el, options)
  File "D:\Softwares\Odoo 13.0\server\odoo\addons\base\models\qweb.py", line 1140, in _compile_directive_foreach
    def_name = self._create_def(options, self._compile_directives(el, options), prefix='foreach', lineno=el.sourceline)
  File "D:\Softwares\Odoo 13.0\server\odoo\addons\base\models\qweb.py", line 675, in _compile_directives
    return compile_handler(el, options)
  File "D:\Softwares\Odoo 13.0\server\odoo\addons\web_editor\models\ir_qweb.py", line 81, in _compile_directive_tag
    return super(QWeb, self)._compile_directive_tag(el, options)
  File "D:\Softwares\Odoo 13.0\server\odoo\addons\base\models\qweb.py", line 1008, in _compile_directive_tag
    content = self._compile_directives(el, options)
  File "D:\Softwares\Odoo 13.0\server\odoo\addons\base\models\qweb.py", line 675, in _compile_directives
    return compile_handler(el, options)
  File "D:\Softwares\Odoo 13.0\server\odoo\addons\base\models\qweb.py", line 1071, in _compile_directive_content
    body.extend(self._compile_node(item, options))
  File "D:\Softwares\Odoo 13.0\server\odoo\addons\base\models\qweb.py", line 654, in _compile_node
    return body + self._compile_directives(el, options)
  File "D:\Softwares\Odoo 13.0\server\odoo\addons\base\models\qweb.py", line 675, in _compile_directives
    return compile_handler(el, options)
  File "D:\Softwares\Odoo 13.0\server\odoo\addons\web_editor\models\ir_qweb.py", line 81, in _compile_directive_tag
    return super(QWeb, self)._compile_directive_tag(el, options)
  File "D:\Softwares\Odoo 13.0\server\odoo\addons\base\models\qweb.py", line 1011, in _compile_directive_tag
    return self._compile_tag(el, content, options, False)
  File "D:\Softwares\Odoo 13.0\server\odoo\addons\base\models\qweb.py", line 977, in _compile_tag
    body.extend(self._compile_all_attributes(el, options, attr_already_created))
  File "D:\Softwares\Odoo 13.0\server\odoo\addons\base\models\qweb.py", line 916, in _compile_all_attributes
    items = self._compile_static_attributes(el, options) + self._compile_dynamic_attributes(el, options)
  File "D:\Softwares\Odoo 13.0\server\odoo\addons\base\models\qweb.py", line 877, in _compile_dynamic_attributes
    nodes.append((name[7:], self._compile_format(value)))
  File "D:\Softwares\Odoo 13.0\server\odoo\addons\base\models\qweb.py", line 1707, in _compile_format
    elts.append(self._compile_strexpr(expr))
  File "D:\Softwares\Odoo 13.0\server\odoo\addons\base\models\qweb.py", line 1667, in _compile_strexpr
    args=[self._compile_expr(expr)], keywords=[],
  File "D:\Softwares\Odoo 13.0\server\odoo\addons\base\models\ir_qweb.py", line 416, in _compile_expr
    st = ast.parse(expr.strip(), mode='eval')
  File "D:\Softwares\Odoo 13.0\python\lib\ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 1
    true ? 'even' : 'odd'
         ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Softwares\Odoo 13.0\server\odoo\http.py", line 624, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "D:\Softwares\Odoo 13.0\server\odoo\http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "D:\Softwares\Odoo 13.0\server\odoo\tools\pycompat.py", line 14, in reraise
    raise value
  File "D:\Softwares\Odoo 13.0\server\odoo\http.py", line 669, in dispatch
    result = self._call_function(**self.params)
  File "D:\Softwares\Odoo 13.0\server\odoo\http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "D:\Softwares\Odoo 13.0\server\odoo\service\model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "D:\Softwares\Odoo 13.0\server\odoo\http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "D:\Softwares\Odoo 13.0\server\odoo\http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "D:\Softwares\Odoo 13.0\server\odoo\http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "D:\Softwares\Odoo 13.0\server\odoo\addons\website_lao_links\controller\main.py", line 15, in render_example_page
    'categories':categories
  File "D:\Softwares\Odoo 13.0\server\odoo\addons\website\models\ir_ui_view.py", line 336, in render
    return super(View, self).render(values, engine=engine, minimal_qcontext=minimal_qcontext)
  File "D:\Softwares\Odoo 13.0\server\odoo\addons\web_editor\models\ir_ui_view.py", line 27, in render
    return super(IrUiView, self).render(values=values, engine=engine, minimal_qcontext=minimal_qcontext)
  File "D:\Softwares\Odoo 13.0\server\odoo\addons\base\models\ir_ui_view.py", line 1185, in render
    return self.env[engine].render(self.id, qcontext)
  File "D:\Softwares\Odoo 13.0\server\odoo\addons\base\models\ir_qweb.py", line 58, in render
    result = super(IrQWeb, self).render(id_or_xml_id, values=values, **context)
  File "D:\Softwares\Odoo 13.0\server\odoo\addons\base\models\qweb.py", line 260, in render
    self.compile(template, options)(self, body.append, values or {})
  File "<decorator-gen-53>", line 2, in compile
  File "D:\Softwares\Odoo 13.0\server\odoo\tools\cache.py", line 90, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "D:\Softwares\Odoo 13.0\server\odoo\addons\base\models\ir_qweb.py", line 113, in compile
    return super(IrQWeb, self).compile(id_or_xml_id, options=options)
  File "D:\Softwares\Odoo 13.0\server\odoo\addons\base\models\qweb.py", line 302, in compile
    raise QWebException("Error when compiling AST", e, path, node and etree.tostring(node[0], encoding='unicode'), name)
odoo.addons.base.models.qweb.QWebException: invalid syntax (<unknown>, line 1)
Traceback (most recent call last):
  File "D:\Softwares\Odoo 13.0\server\odoo\tools\cache.py", line 85, in lookup
    r = d[key]
  File "D:\Softwares\Odoo 13.0\server\odoo\tools\func.py", line 69, in wrapper
    return func(self, *args, **kwargs)
  File "D:\Softwares\Odoo 13.0\server\odoo\tools\lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.qweb', <function IrQWeb.compile at 0x046CCD20>, 580, ('en_US', True, None, None, None, 1))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Softwares\Odoo 13.0\server\odoo\addons\base\models\qweb.py", line 291, in compile
    body = self._compile_node(element, _options)
  File "D:\Softwares\Odoo 13.0\server\odoo\addons\base\models\qweb.py", line 654, in _compile_node
    return body + self._compile_directives(el, options)
  File "D:\Softwares\Odoo 13.0\server\odoo\addons\base\models\qweb.py", line 675, in _compile_directives
    return compile_handler(el, options)
  File "D:\Softwares\Odoo 13.0\server\odoo\addons\web_editor\models\ir_qweb.py", line 81, in _compile_directive_tag
    return super(QWeb, self)._compile_directive_tag(el, options)
  File "D:\Softwares\Odoo 13.0\server\odoo\addons\base\models\qweb.py", line 1008, in _compile_directive_tag
    content = self._compile_directives(el, options)
  File "D:\Softwares\Odoo 13.0\server\odoo\addons\base\models\qweb.py", line 675, in _compile_directives
    return compile_handler(el, options)
  File "D:\Softwares\Odoo 13.0\server\odoo\addons\base\models\qweb.py", line 1071, in _compile_directive_content
    body.extend(self._compile_node(item, options))
  File "D:\Softwares\Odoo 13.0\server\odoo\addons\base\models\qweb.py", line 645, in _compile_node
    return self._compile_static_node(el, options)
  File "D:\Softwares\Odoo 13.0\server\odoo\addons\base\models\qweb.py", line 801, in _compile_static_node
    content = self._compile_directive_content(el, options)
  File "D:\Softwares\Odoo 13.0\server\odoo\addons\base\models\qweb.py", line 1071, in _compile_directive_content
    body.extend(self._compile_node(item, options))
  File "D:\Softwares\Odoo 13.0\server\odoo\addons\base\models\qweb.py", line 645, in _compile_node
    return self._compile_static_node(el, options)
  File "D:\Softwares\Odoo 13.0\server\odoo\addons\base\models\qweb.py", line 801, in _compile_static_node
    content = self._compile_directive_content(el, options)
  File "D:\Softwares\Odoo 13.0\server\odoo\addons\base\models\qweb.py", line 1071, in _compile_directive_content
    body.extend(self._compile_node(item, options))
  File "D:\Softwares\Odoo 13.0\server\odoo\addons\base\models\qweb.py", line 645, in _compile_node
    return self._compile_static_node(el, options)
  File "D:\Softwares\Odoo 13.0\server\odoo\addons\base\models\qweb.py", line 801, in _compile_static_node
    content = self._compile_directive_content(el, options)
  File "D:\Softwares\Odoo 13.0\server\odoo\addons\base\models\qweb.py", line 1071, in _compile_directive_content
    body.extend(self._compile_node(item, options))
  File "D:\Softwares\Odoo 13.0\server\odoo\addons\base\models\qweb.py", line 654, in _compile_node
    return body + self._compile_directives(el, options)
  File "D:\Softwares\Odoo 13.0\server\odoo\addons\base\models\qweb.py", line 675, in _compile_directives
    return compile_handler(el, options)
  File "D:\Softwares\Odoo 13.0\server\odoo\addons\base\models\qweb.py", line 1140, in _compile_directive_foreach
    def_name = self._create_def(options, self._compile_directives(el, options), prefix='foreach', lineno=el.sourceline)
  File "D:\Softwares\Odoo 13.0\server\odoo\addons\base\models\qweb.py", line 675, in _compile_directives
    return compile_handler(el, options)
  File "D:\Softwares\Odoo 13.0\server\odoo\addons\web_editor\models\ir_qweb.py", line 81, in _compile_directive_tag
    return super(QWeb, self)._compile_directive_tag(el, options)
  File "D:\Softwares\Odoo 13.0\server\odoo\addons\base\models\qweb.py", line 1008, in _compile_directive_tag
    content = self._compile_directives(el, options)
  File "D:\Softwares\Odoo 13.0\server\odoo\addons\base\models\qweb.py", line 675, in _compile_directives
    return compile_handler(el, options)
  File "D:\Softwares\Odoo 13.0\server\odoo\addons\base\models\qweb.py", line 1071, in _compile_directive_content
    body.extend(self._compile_node(item, options))
  File "D:\Softwares\Odoo 13.0\server\odoo\addons\base\models\qweb.py", line 654, in _compile_node
    return body + self._compile_directives(el, options)
  File "D:\Softwares\Odoo 13.0\server\odoo\addons\base\models\qweb.py", line 675, in _compile_directives
    return compile_handler(el, options)
  File "D:\Softwares\Odoo 13.0\server\odoo\addons\web_editor\models\ir_qweb.py", line 81, in _compile_directive_tag
    return super(QWeb, self)._compile_directive_tag(el, options)
  File "D:\Softwares\Odoo 13.0\server\odoo\addons\base\models\qweb.py", line 1011, in _compile_directive_tag
    return self._compile_tag(el, content, options, False)
  File "D:\Softwares\Odoo 13.0\server\odoo\addons\base\models\qweb.py", line 977, in _compile_tag
    body.extend(self._compile_all_attributes(el, options, attr_already_created))
  File "D:\Softwares\Odoo 13.0\server\odoo\addons\base\models\qweb.py", line 916, in _compile_all_attributes
    items = self._compile_static_attributes(el, options) + self._compile_dynamic_attributes(el, options)
  File "D:\Softwares\Odoo 13.0\server\odoo\addons\base\models\qweb.py", line 877, in _compile_dynamic_attributes
    nodes.append((name[7:], self._compile_format(value)))
  File "D:\Softwares\Odoo 13.0\server\odoo\addons\base\models\qweb.py", line 1707, in _compile_format
    elts.append(self._compile_strexpr(expr))
  File "D:\Softwares\Odoo 13.0\server\odoo\addons\base\models\qweb.py", line 1667, in _compile_strexpr
    args=[self._compile_expr(expr)], keywords=[],
  File "D:\Softwares\Odoo 13.0\server\odoo\addons\base\models\ir_qweb.py", line 416, in _compile_expr
    st = ast.parse(expr.strip(), mode='eval')
  File "D:\Softwares\Odoo 13.0\python\lib\ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 1
    true ? 'even' : 'odd'
         ^
SyntaxError: invalid syntax

Error when compiling AST
SyntaxError: invalid syntax (<unknown>, line 1)
Template: website_lao_links.s_latest_posts
Path: /t/section/div/ul/t/p
Node: <p t-attf-class="{{ true ? 'even' : 'odd' }}" data-oe-model="ir.ui.view" data-oe-id="580" data-oe-field="arch" data-oe-xpath="/t[1]/section[1]/div[1]/ul[1]/t[1]/p[1]"/>
```

XML file: 
```
<?xml version="1.0" encoding="UTF-8"?>
<odoo>
    

    <template id="s_latest_posts" name="Latest Posts - List">
        <section class="linksSection js_get_posts">
            <div class="container-fluid linksContainer">

                <!-- Tab Menu Section : Start -->
                <ul class="nav nav-tabs nav-fill">
                    <t t-foreach="categories" t-as="category">


                        <p t-attf-class="{{ true ? 'even' : 'odd' }}"></p>
                        <li class="nav-item">
                            <a t-attf-class="nav-link " data-toggle="tab" t-attf-href="#linkTab_{{category.id}}">
                                <t t-esc="category.name" />
                            </a>
                        </li>
                    </t>
                </ul>
                <!-- Tab Menu Section : End -->

                <!-- Tab Content Section : Start -->
                <div class="tab-content">
                    <t t-foreach="categories" t-as="category">
                        <div t-attf-class="tab-pane container " t-attf-id="linkTab_{{category.id}}">
                            <div class="row">
                                <div class="d-flex flex-wrap">
                                    <t t-foreach="links" t-as="link">
                                        <p>
											category.id =
                                            <t t-esc="category.id" />
                                        </p>
                                        <p>
											link.category =
                                            <t t-esc="link.category" />
                                        </p>
                                        <t t-if="category.id == link.category">
                                            <div class="singleLink text-center">
                                                <a href="{{link.url}}" target="_blank">
                                                    <img src="data:image/*;base64,{{link.image}}" alt="" />
                                                </a>
                                                <h3>
                                                    <t t-esc="link.name" />
                                                </h3>
                                            </div>
                                        </t>
                                    </t>
                                </div>
                            </div>
                        </div>
                    </t>
                </div>
                <!-- Tab Content Section : End -->
            </div>
        </section>
    </template>
    <template id="s_latest_posts_place_into_bar" inherit_id="website.snippets" name="s_latest_posts Place into bar">
        <xpath expr="//div[@id='snippet_feature']/div[@class='o_panel_body']" position="inside">
            <t t-snippet="website_lao_links.s_latest_posts" t-thumbnail="/website_lao_links/static/src/img/icon.png" />
        </xpath>
    </template>
</odoo>
```

**Note:** I did not test this issue other versions of odoo

**Comment by ged-odoo** [comment]
@SoftHeroes Thank you for your input.  Looking at your tracebacks, the issue that you encounter is actually inside the QWeb python engine in Odoo. You are working with templates that are rendered by the server for an odoo website.

This repository is only about Owl, the JS framework in use for Odoo javascript code (but only the part that is rendered by the browser). 

Also, note that QWeb has several implementations, but no formal specification.  Owl extends the QWeb specification by adding a few directives, and also, by fixing a few bugs/usability bugs, such as this one.
